name: sigrid-publish
on:
  push:
    branches:
      - "master"
      
env:
  SIGRID_CI_CUSTOMER: 4mendix
  SIGRID_CI_SYSTEM: communitycommons
  
  
jobs:
  sigridci:
    name: Sigrid CI Publish
    runs-on: ubuntu-latest
    container:
      image: softwareimprovementgroup/mendixpreprocessor:latest
      env: 
        SIGRID_CI_PUBLISH: publishonly
        SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
    steps:
      - run: ""
